/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:5b7d3258-e49e-42d2-b56a-f64f8450ce78",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_8S591MWjJ",
    "aws_user_pools_web_client_id": "1fgf9s67j98jafpgcqe280epu7",
    "oauth": {}
};


export default awsmobile;
