/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:e54e7223-d1ba-43fc-bf02-fe0dc463b687",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_wKJi0mVHF",
    "aws_user_pools_web_client_id": "3g886ullpq4itejh3gsjj901o7",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://iljurl2mxvepdjlkwbt3g2a6d4.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3ny7gxqv5vbfnkwvtkzcbn57ge",
    "aws_user_files_s3_bucket": "amplifyappe5ffcf9acff2494da58683e895eb2e4c124115-staging",
    "aws_user_files_s3_bucket_region": "ap-southeast-2"
};


export default awsmobile;
