/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:e54e7223-d1ba-43fc-bf02-fe0dc463b687",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_wKJi0mVHF",
    "aws_user_pools_web_client_id": "3g886ullpq4itejh3gsjj901o7",
    "oauth": {}
};


export default awsmobile;
